version: '3.8'
services:
  db:
    image: postgres:14.7-alpine
    container_name: postgres_docker
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - docker_net
    volumes:
      - dataDB:/usr/var/wwww

networks:
  docker_net:
    driver: bridge

volumes:
  dataDB:
    driver: local
